# Generated by Django 5.1.3 on 2024-11-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favortie',
            new_name='favorties',
        ),
    ]
